### PR TITLE
Fix buildtype=debug

### PR DESCRIPTION
**Pull request by gtmills**
2 fixes here, both are legit potential bugs, especially the 2nd.

1)  Fix potential null pointer dereference
When building with buildtype=debug:
| ../git/include/dump_offload.hpp:168:34: error: potential nullreference]
|   168 |                 this->dumpSize = *dumpsize;
|       |
This has been a issue for a while.
Slack discussion here on this:
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1635947639390400
I took this fix from https://github.ibm.com/openbmc/bmcweb/pull/89/files

2)  Bail if controlMode is invalid  
This error was introduced in #135
When buildtype=debug:
../lib/environment_metrics.hpp:354:52: error: 'powerCapEnable' may be used
uninitialized in this function [-Werror=maybe-uninitialized]
Add the return.

Tested: bmcweb builds with buildtype=debug. Did not do any further testing.

### CODE REVIEW

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/170 should fix this CI fail

**Comment by gtmills** [comment]
jenkins run tests please

**Review by patelabhishek9893 — APPROVED** [review]

**Review by geissonator — APPROVED** [review]
